"""catalogos delivery method y bill document type, municipality completo

Revision ID: 0b0c3f374506
Revises: c5808909d6e9
Create Date: 2026-08-13 13:22:19.204812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b0c3f374506'
down_revision: Union[str, Sequence[str], None] = 'c5808909d6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woo_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sap_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_document_types_woo_code'), 'bill_document_types', ['woo_code'], unique=True)
    op.create_table('delivery_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woo_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sap_sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_methods_woo_code'), 'delivery_methods', ['woo_code'], unique=True)
    op.add_column('municipalities', sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('municipalities', sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.alter_column('municipalities', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('municipalities', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('municipalities', 'state_code')
    op.drop_column('municipalities', 'city_name')
    op.drop_index(op.f('ix_delivery_methods_woo_code'), table_name='delivery_methods')
    op.drop_table('delivery_methods')
    op.drop_index(op.f('ix_bill_document_types_woo_code'), table_name='bill_document_types')
    op.drop_table('bill_document_types')
    # ### end Alembic commands ###
