"""Agrega purchase_order_code a woo_orders y sap_billings

Revision ID: 487821635203
Revises: 25f41acdd5b1
Create Date: 2026-09-04 13:34:27.345093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '487821635203'
down_revision: Union[str, Sequence[str], None] = '25f41acdd5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_billings', sa.Column('purchase_order_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('woo_orders', sa.Column('purchase_order_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('woo_orders', 'purchase_order_code')
    op.drop_column('sap_billings', 'purchase_order_code')
    # ### end Alembic commands ###
