"""add failures table

Revision ID: 79e3d05f4c0a
Revises: f676964ae4e1
Create Date: 2026-08-18 09:02:12.778398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79e3d05f4c0a'
down_revision: Union[str, Sequence[str], None] = 'f676964ae4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_entity_id'), 'failures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_failures_entity_type'), 'failures', ['entity_type'], unique=False)
    op.create_index(op.f('ix_failures_notified'), 'failures', ['notified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failures_notified'), table_name='failures')
    op.drop_index(op.f('ix_failures_entity_type'), table_name='failures')
    op.drop_index(op.f('ix_failures_entity_id'), table_name='failures')
    op.drop_table('failures')
    # ### end Alembic commands ###
