"""modelo sap_invoice

Revision ID: 84e55f1cd022
Revises: dfb673c67533
Create Date: 2026-08-13 15:41:35.034799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84e55f1cd022'
down_revision: Union[str, Sequence[str], None] = 'dfb673c67533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_invoices',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'EXHAUSTED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sap_billing_id', sa.Integer(), nullable=True),
    sa.Column('doc_entry', sa.Integer(), nullable=False),
    sa.Column('doc_num', sa.Integer(), nullable=True),
    sa.Column('folio', sa.Integer(), nullable=True),
    sa.Column('folio_prefix', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('doc_type_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('seller_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('pdf_base64', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sap_billing_id'], ['sap_billings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_invoices_doc_entry'), 'sap_invoices', ['doc_entry'], unique=True)
    op.create_index(op.f('ix_sap_invoices_sap_billing_id'), 'sap_invoices', ['sap_billing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_invoices_sap_billing_id'), table_name='sap_invoices')
    op.drop_index(op.f('ix_sap_invoices_doc_entry'), table_name='sap_invoices')
    op.drop_table('sap_invoices')
    # ### end Alembic commands ###
