"""modelo woo_order

Revision ID: 9bf33f188496
Revises: ebfc73d26aac
Create Date: 2026-08-13 14:40:10.435626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bf33f188496'
down_revision: Union[str, Sequence[str], None] = 'ebfc73d26aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woo_orders',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'EXHAUSTED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('shipping', sa.Integer(), nullable=False),
    sa.Column('pay_auth_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('delivery_method_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('bill_doc_type_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('customer_tax_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_woo_orders_code'), 'woo_orders', ['code'], unique=True)
    op.alter_column('sap_customers', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sap_customers', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.drop_index(op.f('ix_woo_orders_code'), table_name='woo_orders')
    op.drop_table('woo_orders')
    # ### end Alembic commands ###
