"""sap customers y catalogos de referencia

Revision ID: c5808909d6e9
Revises: e4bcb6587668
Create Date: 2026-08-13 13:12:01.228656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5808909d6e9'
down_revision: Union[str, Sequence[str], None] = 'e4bcb6587668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woo_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sap_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_woo_code'), 'industries', ['woo_code'], unique=True)
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woo_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sap_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipalities_woo_code'), 'municipalities', ['woo_code'], unique=True)
    op.create_table('sap_customers',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'EXHAUSTED', name='sync_status', native_enum=False), nullable=True),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('contact_code', sa.Integer(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bill_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bill_row', sa.Integer(), nullable=False),
    sa.Column('ship_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ship_row', sa.Integer(), nullable=False),
    sa.Column('business_activity', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_customers_tax_id'), 'sap_customers', ['tax_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_customers_tax_id'), table_name='sap_customers')
    op.drop_table('sap_customers')
    op.drop_index(op.f('ix_municipalities_woo_code'), table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_index(op.f('ix_industries_woo_code'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
