"""modelo sap_billing

Revision ID: dfb673c67533
Revises: 9bf33f188496
Create Date: 2026-08-13 14:52:17.534569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfb673c67533'
down_revision: Union[str, Sequence[str], None] = '9bf33f188496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_billings',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'EXHAUSTED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woo_order_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('doc_type_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('internal_notes', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('public_notes', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=True),
    sa.Column('pay_auth_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('doc_entry', sa.Integer(), nullable=True),
    sa.Column('doc_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['woo_order_id'], ['woo_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('woo_order_id', 'chunk_index')
    )
    op.create_index(op.f('ix_sap_billings_woo_order_id'), 'sap_billings', ['woo_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_billings_woo_order_id'), table_name='sap_billings')
    op.drop_table('sap_billings')
    # ### end Alembic commands ###
