"""extender sap_customer con campos de payload real

Revision ID: ebfc73d26aac
Revises: 0b0c3f374506
Create Date: 2026-08-13 14:06:15.404407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebfc73d26aac'
down_revision: Union[str, Sequence[str], None] = '0b0c3f374506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_customers', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('sap_customers', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('industry_sap_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('sap_customers', sa.Column('contact_first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('sap_customers', sa.Column('contact_last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('sap_customers', sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('sap_customers', sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('bill_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('bill_municipality_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sap_customers', sa.Column('bill_municipality_city_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sap_customers', sa.Column('bill_municipality_state_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('ship_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sap_customers', sa.Column('ship_municipality_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sap_customers', sa.Column('ship_municipality_city_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sap_customers', sa.Column('ship_municipality_state_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_customers', 'ship_municipality_state_code')
    op.drop_column('sap_customers', 'ship_municipality_city_name')
    op.drop_column('sap_customers', 'ship_municipality_name')
    op.drop_column('sap_customers', 'ship_address')
    op.drop_column('sap_customers', 'bill_municipality_state_code')
    op.drop_column('sap_customers', 'bill_municipality_city_name')
    op.drop_column('sap_customers', 'bill_municipality_name')
    op.drop_column('sap_customers', 'bill_address')
    op.drop_column('sap_customers', 'contact_email')
    op.drop_column('sap_customers', 'contact_phone')
    op.drop_column('sap_customers', 'contact_last_name')
    op.drop_column('sap_customers', 'contact_first_name')
    op.drop_column('sap_customers', 'industry_sap_code')
    op.drop_column('sap_customers', 'email')
    op.drop_column('sap_customers', 'phone')
    op.drop_column('sap_customers', 'name')
    # ### end Alembic commands ###
