"""add emails table

Revision ID: f676964ae4e1
Revises: 84e55f1cd022
Create Date: 2026-08-13 16:02:39.027123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f676964ae4e1'
down_revision: Union[str, Sequence[str], None] = '84e55f1cd022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'EXHAUSTED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('sap_invoice_id', sa.Integer(), nullable=True),
    sa.Column('woo_order_id', sa.Integer(), nullable=True),
    sa.Column('to', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('brevo_message_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sap_invoice_id'], ['sap_invoices.id'], ),
    sa.ForeignKeyConstraint(['woo_order_id'], ['woo_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_sap_invoice_id'), 'emails', ['sap_invoice_id'], unique=False)
    op.create_index(op.f('ix_emails_woo_order_id'), 'emails', ['woo_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_woo_order_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sap_invoice_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
